#!/bin/sh

if [ "$1" = menu ]; then
    boot-menu-add-entry "$0" "nand_alt (UBI)"
    exit
fi

#bootargs-ip
bootargs-display

global.bootm.image="/dev/nand0.kernel.bb"
#global.bootm.oftree="/env/oftree"
global.linux.bootargs.dyn.root="root=ubi0:root_alt ubi.mtd=8 rootfstype=ubifs"
