#!/bin/sh

# ip setting (static/dhcp)
ip=static
global.dhcp.vendor_id=barebox-${global.hostname}

# static setup used if ip=static
ipaddr=172.16.40.53
netmask=255.255.255.0
gateway=192.168.3.10
serverip=172.16.40.113
