#!/bin/sh

# board defaults, do not change in running system. Change /env/config
# instead
global linux.bootargs.dyn.display

global.hostname=pcm051
global.linux.bootargs.base="console=ttyO0,115200 loglevel=7"
